#!/bin/bash

export $(cat .env | grep -v '^#' | xargs)

docker run -it --rm \
  --publish ${AUTHN_URL##*:}:3000 \
  -e DATABASE_URL=sqlite3://:memory:?mode=memory\&cache=shared \
  -e SECRET_KEY_BASE \
  -e HTTP_AUTH_USERNAME \
  -e HTTP_AUTH_PASSWORD \
  -e APP_DOMAINS \
  -e AUTHN_URL \
  -e GITHUB_OAUTH_CREDENTIALS \
  --name authn_demo \
  keratin/authn-server:1.4.1 \
  sh -c "./authn migrate && ./authn server"
